apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-deployment
  labels:
    type: front-end
spec: 
  selector:
      type: front-end
  replicas: 3
  template:
    metadata:
      labels:
        type: front-end
  spec:
     containers:
        - name: nginxcontainer
          image: nginx:latest
    
  